FORMAT: 1A
HOST: http://duan.dev/

# Duan

Duan is a simple app to help you generate shortened urls.

## Duan Collection [/api/duan]

### List All Duan [GET]

+ Request (application/json)

+ Response 200 (application/json)

        [
          {
            "hash": "t",
            "url": "https://twitter.com/",
            "customized": "1",
            "created_at": {
              "date": "2016-09-27 10:53:02.000000",
              "timezone_type": 3,
              "timezone": "Europe/Berlin"
            },
            "updated_at": {
              "date": "2016-09-27 10:53:02.000000",
              "timezone_type": 3,
              "timezone": "Europe/Berlin"
            }
          },
          {
            "hash": "Y2I4Zm",
            "url": "http://duan.dev/",
            "customized": "0",
            "created_at": {
              "date": "2016-09-27 10:53:02.000000",
              "timezone_type": 3,
              "timezone": "Europe/Berlin"
            },
            "updated_at": {
              "date": "2016-09-27 10:53:02.000000",
              "timezone_type": 3,
              "timezone": "Europe/Berlin"
            }
          }
        ]

### Create a New Duan [POST]

You may create your own duan using this action. It takes a JSON
object containing a url and an optional hash.

+ Request (application/json)

        {
            "hash": "t",
            "url": "https://twitter.com/"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/duan/t

    + Body

            {
                "hash": "t",
                "url": "https://twitter.com/",
                "customized": "1",
                "created_at": {
                    "date": "2016-09-27 10:51:59.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Berlin"
                  },
                "updated_at": {
                    "date": "2016-09-27 10:51:59.000000",
                    "timezone_type": 3,
                    "timezone": "Europe/Berlin"
                }
            }
