#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Duan\Console\UserCreator;

require __DIR__ . "/vendor/autoload.php";

$app = new Application();
$app->setName('Rogue. cli to manage Duan application.');

$app->add(new UserCreator());

$app->run();
